version: "3.8"
services:
  dev-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3306
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password_trial
      MYSQL_DATABASE: db_trial
      MYSQL_USER: user_trial
      MYSQL_PASSWORD: password_trial
    restart: always
    networks:
      - lesson
networks:
  lesson:
